const animalCares = [
  {
    id: 1,
    animal: "Dog",
    food: "Dog Food",
    exercise: "Daily Walks",
    grooming: "Weekly Grooming",
  },
  {
    id: 2,
    animal: "Cat",
    food: "Cat Food",
    exercise: "Playtime",
    grooming: "Occasional Brushing",
  },
  {
    id: 3,
    animal: "Rabbit",
    food: "Hay and Vegetables",
    exercise: "Room to Hop",
    grooming: "Regular Brushing",
  },
  {
    id: 4,
    animal: "Fish",
    food: "Fish Flakes",
    exercise: "Swimming",
    grooming: "Tank Cleaning",
  },
  {
    id: 5,
    animal: "Parrot",
    food: "Seeds and Fruits",
    exercise: "Flying",
    grooming: "Beak and Nail Trimming",
  },
  {
    id: 6,
    animal: "Hamster",
    food: "Hamster Mix",
    exercise: "Wheel Running",
    grooming: "Occasional Brushing",
  },
  {
    id: 7,
    animal: "Guinea Pig",
    food: "Vegetables and Pellets",
    exercise: "Playtime",
    grooming: "Regular Brushing",
  },
  {
    id: 8,
    animal: "Turtle",
    food: "Turtle Pellets",
    exercise: "Swimming",
    grooming: "Shell Cleaning",
  },
  {
    id: 9,
    animal: "Horse",
    food: "Hay and Oats",
    exercise: "Daily Riding",
    grooming: "Daily Brushing",
  },
  {
    id: 10,
    animal: "Snake",
    food: "Mice",
    exercise: "Slithering",
    grooming: "Shedding Assistance",
  },
  {
    id: 11,
    animal: "Ferret",
    food: "Ferret Food",
    exercise: "Playtime",
    grooming: "Occasional Bathing",
  },
  {
    id: 12,
    animal: "Chicken",
    food: "Chicken Feed",
    exercise: "Foraging",
    grooming: "Coop Cleaning",
  },
  {
    id: 13,
    animal: "Goat",
    food: "Grass and Hay",
    exercise: "Grazing",
    grooming: "Hoof Trimming",
  },
  {
    id: 14,
    animal: "Pig",
    food: "Pig Feed",
    exercise: "Outdoor Play",
    grooming: "Occasional Bathing",
  },
  {
    id: 15,
    animal: "Cow",
    food: "Grass and Silage",
    exercise: "Grazing",
    grooming: "Regular Brushing",
  },
  {
    id: 16,
    animal: "Sheep",
    food: "Grass and Hay",
    exercise: "Grazing",
    grooming: "Shearing",
  },
  {
    id: 17,
    animal: "Duck",
    food: "Duck Pellets",
    exercise: "Swimming",
    grooming: "Feather Maintenance",
  },
  {
    id: 18,
    animal: "Goose",
    food: "Goose Pellets",
    exercise: "Swimming",
    grooming: "Feather Maintenance",
  },
  {
    id: 19,
    animal: "Lizard",
    food: "Insects",
    exercise: "Climbing",
    grooming: "Shedding Assistance",
  },
  {
    id: 20,
    animal: "Frog",
    food: "Insects",
    exercise: "Hopping",
    grooming: "Tank Cleaning",
  },
  {
    id: 21,
    animal: "Chinchilla",
    food: "Chinchilla Pellets",
    exercise: "Playtime",
    grooming: "Dust Bath",
  },
  {
    id: 22,
    animal: "Gerbil",
    food: "Gerbil Mix",
    exercise: "Wheel Running",
    grooming: "Occasional Brushing",
  },
  {
    id: 23,
    animal: "Hedgehog",
    food: "Insects and Cat Food",
    exercise: "Playtime",
    grooming: "Nail Trimming",
  },
  {
    id: 24,
    animal: "Budgie",
    food: "Seeds",
    exercise: "Flying",
    grooming: "Nail Trimming",
  },
  {
    id: 25,
    animal: "Lovebird",
    food: "Seeds and Fruits",
    exercise: "Flying",
    grooming: "Beak and Nail Trimming",
  },
  {
    id: 26,
    animal: "Canary",
    food: "Seeds",
    exercise: "Flying",
    grooming: "Nail Trimming",
  },
  {
    id: 27,
    animal: "Finch",
    food: "Seeds",
    exercise: "Flying",
    grooming: "Nail Trimming",
  },
  {
    id: 28,
    animal: "Cockatiel",
    food: "Seeds and Pellets",
    exercise: "Flying",
    grooming: "Beak and Nail Trimming",
  },
  {
    id: 29,
    animal: "Pigeon",
    food: "Grains",
    exercise: "Flying",
    grooming: "Occasional Bathing",
  },
  {
    id: 30,
    animal: "Peacock",
    food: "Grains and Insects",
    exercise: "Foraging",
    grooming: "Feather Maintenance",
  },
]

export default animalCares
